// Code generated by Slice Machine. DO NOT EDIT.

import ProjectHero from "./ProjectHero/index.svelte";
import ProjectList from "./ProjectList/index.svelte";
import Welcome from "./Welcome/index.svelte";

export const components = {
  project_hero: ProjectHero,
  project_list: ProjectList,
  welcome: Welcome,
};
