// Code generated by Slice Machine. DO NOT EDIT.

import GekkeDingen from "./GekkeDingen/index.svelte";
import Test from "./Test/index.svelte";
import TextBlock from "./TextBlock/index.svelte";

export const components = {
  gekke_dingen: GekkeDingen,
  test: Test,
  text_block: TextBlock,
};
